name: Docker CI CMS

on:
  push:
    branches: [main]
    paths:
      - 'cms/**'
jobs:

  build_and_push:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "secrets.json"
        json: ${{ secrets.SECRETS_JSON_CLIENT }}
        dir: 'Ecothon.Web/'


    - name: Build the CMS Docker image
      run: docker build . --file ./cms/Dockerfile --tag ${{secrets.DOCKER_USER}}/ecothon-cms:latest
      
    - name: Docker push CMS image
      run: docker push ${{secrets.DOCKER_USER}}/ecothon-cms