name: Github Pages CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Ecothon.Web/**'
      - 'Ecothon.Dtos/**'
      - '.github/workflows/gh-pages.yml'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    - run: dotnet publish .\Ecothon.Web\
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@releases/v3                             
      with:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  
        FOLDER: Ecothon.Web/bin/Release/net8.0/publish/wwwroot